### ISSUE TITLE
Consul backed Secret Store

### ISSUE THREAD

**Issue by trane** [lookout/borderpatrol#40]
We currently have an `InMemorySecretStore` that does well for mocking, but we need to store `Secrets` somewhere that provides a consistent view of the current state of `Secrets`.

Obviously, Zookeeper is a great place to store these things, but since we have a use-case for Consul as well.

All that needs to be done is to provide a Consul backend for a `SecretStoreApi` interface, making sure it is as purely functional as you can -- why not have the entire state of everything ever forever?

**Comment by trane** [comment]
So I think of this as a few abstractions:
 * a way to store into consul (serialize to json) external to individual server processes
 * a way to cache secrets in-memory to avoid fetching from consul constantly
 * a way to poll/watch consul for new secrets

**Comment by PeterFCaswell** [comment]
Why the cache? Fetching from consul should be a fast as memcache.
I can understand we might want a caching mechanism at the SecretStore level, but for the InMemorySecretStore and the ConsulSecretStore, it should be a no-op. I would think.

**Comment by PeterFCaswell** [comment]
Here are more thoughts on this.

I think I'd consider the abstract SecretStore to be comprised of (forgive the Javaish terminology):
  1. Medium Interface
  2. Serializer
  3. Caching Policy
  4. Polling Policy (which also needs the Medium Interface).

The medium interface is straightforward, or should be: a way to read/write/create/delete, whatever.

The serializer is likewise straightforward. Though I wonder if it needs an interface for serializing the key as well as the data.

The caching policy is something that could be generic across multiple objects. Especially we don't expect to read and write through the cache (and are willing to query cache, then medium). For through-caches, this'll need to have the medium interface. The simplest cache is obviously no cache. And there are no end to caching strategies. They can even be stacked.

The Polling policy needs the medium interface, but it can also be a no-op if that's what one wants.

Genericizng the policies gives you some hope of reusing them outside the project, or even of pulling in other code for the policies. It also gives you the chance to change them based on configuration parameters rather than code. And that would hopefully alleviate your concerns about spof or throughput on your storage medium.

**Comment by trane** [comment]
@PeterFCaswell yes, sounds like we are looking at this exactly the same way.

There are two existing interfaces already defined in bp:

`SecretStoreApi` which is the only interface for clients to retrieve the `current` and `previous` rotating secrets, see: `sessionx.SecretStoreApi`.

also, serializing is defined in the `Encoder` type class (`SecretEncoder`) - and reusable.

**Comment by trane** [comment]
The concerns for caching aren't for throughput due to the storage medium, it is to reduce the object creation (and therefore gc and serialization/deserialization) for these secrets.

**Comment by tejom** [comment]
I was working on this issue a little. I think there needs to be some consul specific functions added. I don' t know where the appropriate place for those would be. 

https://github.com/tejom/borderpatrol/blob/consul-secretapi/core/src/main/scala/com/lookout/borderpatrol/sessionx/SecretStores.scala

Bit of a mess so far and incomplete

**Comment by trane** [comment]
Nice @tejom! We can sit down and talk through some of it if you'd like to. I have a direction I am thinking of going, but if we can make your implementation work with a bit of polishing then I'm happy to move forward with it :)

**Comment by tejom** [comment]
Thanks @trane .  Yeah that sounds good.

**Comment by trane** [comment]
Once we have configuration instantiating this, we can go ahead and close it. @maheshkelkar is going to work on that.
